### ISSUE TITLE
basic auth failed

### ISSUE THREAD

**Issue by jney** [mafr/docker-squid#1]
hi. i'm trying to use the container

i executed the following command declaring password foobar

```
$ htdigest conf/passwd SurfinUSA myuser
```

after launching the container, i tried that :

```
$ curl -x $(docker-machine ip default):4712 -u myuser:foobar http://google.com
```

but i got page saying : 

``` html
<div id="titles">
<h1>ERROR</h1>
<h2>Cache Access Denied.</h2>
</div>
<hr>
```

**Comment by mafr** [comment]
I think you need the --proxy-user switch to authenticate, not the plain --user switch (-u vs -U). Also, the --proxy-digest switch might help.

**Comment by jney** [comment]
my bad. works better now. thank you

**Comment by mafr** [comment]
Great - thanks for your feedback!
